[tools]
"npm:@earendil-works/pi-coding-agent" = "0.84.3"
"npm:context-mode" = "1.0.169"
"npm:@fission-ai/openspec" = "1.10.0"
ast-grep = "0.45.2"
difftastic = "0.70.0"
fd = "10.4.2"
# renovate: datasource=github-releases depName=nushell/nushell
"aqua:nushell/nushell" = "0.115.1"
shellcheck = "0.11.0"
yq = "4.53.6"
